### ISSUE TITLE
Clarification on Behavior of f(i=2, i=1) in C++17

### ISSUE THREAD

**Issue by D4arkShad0w** [federico-busato/Modern-CPP-Programming#104]
The slide from the "Basic Concept I" presentation (Slide 26) indicates that f(i=2, i=1), which previously exhibited undefined behavior, now has defined behavior in C++17, resulting in i being assigned 2. However, C++17 specifies that the order of evaluation of function arguments is unspecified, not strictly defined. This means that the evaluation order is not guaranteed to be consistent and could vary between different implementations.

Clang Trunk Sample With C++20 Enabled : https://godbolt.org/z/5h89TYE1n

**Comment by federico-busato** [comment]
thanks for the question. The slide is correct. The compilers (clang/gcc) are very conservative for this kind of situation. They issue a warning even when the behavior is well-defined (>= C++17) to prevent error-prone code. see https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wsequence-point
