### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by luck-tian** [federico-busato/Modern-CPP-Programming#106]
path: 18.Iterators_Containers_Alg.pdf

![WXWorkCapture_17224157708788](https://github.com/user-attachments/assets/84046670-4d14-4be0-a45e-44c921787cbb)
 there's a syntax error in that code snippet due to a missing closing parenthesis

**Comment by federico-busato** [comment]
thanks for reporting it, @luck-tian. I will fix it soon
