### ISSUE TITLE
Typo in 07.Object_Oriented_II.pdf

### ISSUE THREAD

**Issue by kimsoohwan** [federico-busato/Modern-CPP-Programming#11]
Hi Federico,

Hope you're doing well.
I think I found another typo. :-)

In the second option on Page 47/61 in 07.Object_Oriented_II.pdf,
I think "swap(this, x);" should be "swap(*this, x);".
The declaration in the next page says "void swap(A& x, A&y);" 
and thus instead of passing the this pointer, I think we need to pass the object after dereferencing.

Hope this helpful for improving your work.
Thank you very much again.

Kind regards,
Soohwan

**Comment by federico-busato** [comment]
Hi @kimsoohwan, thanks for the contribution! just updated the slides 😊
