### ISSUE TITLE
A commentary mistake about 'struct Member Access' in 06.Bascis_concepts_IV

### ISSUE THREAD

**Issue by hsunchiu** [federico-busato/Modern-CPP-Programming#111]
In the page 52/92, 
```cpp
struct A{
int x;
};
.....

ptr->x;     // arrow syntax: same of *ptr.x
//                                   /\  mistake here
```
please change to 
`ptr->x // arrow syntax: same of (*ptr).x`

**Comment by federico-busato** [comment]
thank you for reporting it, @hsunchiu. Actually, this little issue made me think about slightly rearranging the order of some slides and adding subsections to improve readability.
