### ISSUE TITLE
Sharing the template

### ISSUE THREAD

**Issue by roshankarande** [federico-busato/Modern-CPP-Programming#112]
Hi,

I wanted to make a similar repository for Rust Programming Language. Do you mind sharing the template used for generation of these pdfs and html?

Thanks,

**Comment by fbusato** [comment]
Hi, it would be great to have a similar course for Rust :).
I used [Metropolis](https://github.com/matze/mtheme) as latex beamer theme and [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX) to generate the htmls
