### ISSUE TITLE
Feedback on compiler installation instructions on Linux, slide 10/22 in 02.Preparation slidedeck

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [federico-busato/Modern-CPP-Programming#115]
![image](https://github.com/user-attachments/assets/638945a1-7552-4955-b069-7ea2df1c1d07)

I suspect that the first command (`bash -c`) executes the `llvm.sh` script. 

The same is also accomplished by the next three commands (download, change permissions, execute). 

If my assessment is accurate, the installation instruction can be simplified.

I suggest to remove the `bash -c` command since it also requires `sudo` privileges to execute.

**Comment by federico-busato** [comment]
agree! thanks
