### ISSUE TITLE
Typo on slide "Dynamic memory allocation and OS", slide 35/93 in deck 06.Basic_Concepts_IV

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [federico-busato/Modern-CPP-Programming#116]
![image](https://github.com/user-attachments/assets/e172b537-960c-43e9-934c-85f14976ff2c)

Suggested text is:

>  "..., it asks for a chunk of memory *from* the OS".

**Comment by federico-busato** [comment]
thanks!
