### ISSUE TITLE
Clarification needed on "constexpr Functions -Constraints" slide

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [federico-busato/Modern-CPP-Programming#118]
![image](https://github.com/user-attachments/assets/0c389afd-818d-4295-a92e-6854e2882735)

I think the second bullet point should be that "*does not* contain run-time functions".

**Comment by federico-busato** [comment]
Hi @oleksandr-pavlyk, the second bullet looks right. Perhaps it is the double use of the term "runtime" that may confuse.

**Comment by federico-busato** [comment]
thank you again, @oleksandr-pavlyk. I appreciated your time on pointing out typos in the text
