### ISSUE TITLE
Typo report in 07.Object_Oriented_II.pdf

### ISSUE THREAD

**Issue by kimsoohwan** [federico-busato/Modern-CPP-Programming#13]
Hi Federico,

Just spotted another little typo. :-)
On Page 48/61 in in 07.Object_Oriented_II.pdf, you might want "y.Array" to be "y.array".
By the way, I really like your idea of making a copy and swapping it with the current object.

Thanks a bunch once again.
Wishing you a cozy weekend.

Kind regards,
Soohwan

**Comment by fbusato** [comment]
Hi Soohwan, thanks again! sorry for the delay, I was pretty busy during the long weekend. 

> By the way, I really like your idea of making a copy and swapping it with the current object.

By the way, this is not something I invented. It is fine for objects with simple semantics, but might be tricky to use in complex cases.
