### ISSUE TITLE
Warn that 'using namespace std' is a bad practice

### ISSUE THREAD

**Issue by jesustorresdev** [federico-busato/Modern-CPP-Programming#20]
It is understandable that 'using namespace std' is used for educational reasons, but then I think it should be pointed out somewhere in the text that it is done for that reason, but is currently considered bad practice in any style guide.

**Comment by federico-busato** [comment]
yes, you are perfectly right. This is mentioned in the slide set `13.Code Convention`, section `namespace`, slide 32
