### ISSUE TITLE
feature-request: all-in-one pdf

### ISSUE THREAD

**Issue by csukuangfj** [federico-busato/Modern-CPP-Programming#25]
Thank you for making the book public.

Could you provide an all-in-one.pdf ?

**Comment by pulmark** [comment]
The following shell script in Linux combines files into single pdf file (uses ghostscript):

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=combined-all.pdf \
01.Introduction.pdf \
02.Basic_Concepts_I.pdf \
03.Basic_Concepts_II.pdf \
04.Basic_Concepts_III.pdf \
05.Basic_Concepts_IV.pdf \
06.Basic_Concepts_V.pdf \
07.Object_Oriented_I.pdf \
08.Object_Oriented_II.pdf \
09.Templates_I.pdf \
10.Templates_II.pdf \
11.Translation_Units_I.pdf \
12.Translation_Units_II.pdf \
13.Code_Convention.pdf \
14.Ecosystem_I.pdf \
15.Ecosystem_II.pdf \
16.Utilities.pdf \
17.Iterators_Containers_Alg.pdf \
18.Advanced_Topics_I.pdf \
19.Advanced_Topics_II.pdf \
20.Optimization_I.pdf \
21.Optimization_II.pdf \
22.Optimization_III.pdf \

**Comment by federico-busato** [comment]
@pulmark thanks for providing the command. GhostScript is pretty slow with all these slides 😅 
@csukuangfj all-in-one book added, even if I don't fully understand why it is useful

**Comment by csukuangfj** [comment]
> @csukuangfj all-in-one book added, even if I don't fully understand why it is useful

Thank you!

all-in-one.pdf makes it easier to read the book on a device and it also makes it easier to search something through the book.
