### ISSUE TITLE
Typo in 02.Basic_Concepts_I.pdf

### ISSUE THREAD

**Issue by csukuangfj** [federico-busato/Modern-CPP-Programming#26]
Please see the figure below for the typo

# 1/6

![Screenshot 2023-12-03 at 16 55 13](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/1337b152-a255-427a-9dc5-736e759729e9)

# 2/6
![Screenshot 2023-12-03 at 17 00 13](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/99a6e904-b7e7-44b6-8e4a-850df2303600)
# 3/6
![Screenshot 2023-12-03 at 17 02 53](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/5b0d01fa-a448-4992-a9aa-0c6ee8e94241)

# 4/6
![Screenshot 2023-12-03 at 17 05 50](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/6f342c08-b5eb-458c-9f84-940dbff9a124)
# 5/6
![Screenshot 2023-12-03 at 17 11 47](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/6db4db5e-d65e-4732-99d1-d9115fefc0b7)
# 6/6
![Screenshot 2023-12-03 at 17 21 52](https://github.com/federico-busato/Modern-CPP-Programming/assets/5284924/9c174537-0099-4591-8418-39ba3d11d828)

**Comment by federico-busato** [comment]
@csukuangfj good catch. Some of them were difficult to find. Thank you for reporting them!
