### ISSUE TITLE
what is the font used in the examples 

### ISSUE THREAD

**Issue by atulsingh14** [federico-busato/Modern-CPP-Programming#3]
Hey, Sorry if this is not the right place to do this. But i am very curious about the the font you have used in the examples in the pdf.
Reference on Page 12 in Indtroduction.pdf.

**Comment by federico-busato** [comment]
Hi, I'm using the **minted** package for all code examples with the default configuration https://www.overleaf.com/learn/latex/Code_Highlighting_with_minted
