### ISSUE TITLE
Code conventions typo

### ISSUE THREAD

**Issue by dsardelic** [federico-busato/Modern-CPP-Programming#34]
In [13.Code_Convention.pdf](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/13.Code_Convention.pdf) on page marked 60/80 (absolute page 71/95) it says "Use `noexpect` instead" where it should say "Use `noexcept` instead".

**Comment by federico-busato** [comment]
@dsardelic Thank you for reporting it
