### ISSUE TITLE
11.Translation_Units_I.pdf, inline constexpr variables linkage

### ISSUE THREAD

**Issue by guoci** [federico-busato/Modern-CPP-Programming#40]
On page 34, the variable `inline constexpr int y = 3;` is labeled as having internal linkage. I think that is supposed to be `external linkage`.
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/1260178/822c9617-7fb9-4ef0-a970-8070da183bd9)

**Comment by federico-busato** [comment]
Hi @guoci, probably you are interpreting the `inline` keyword in the wrong way. `inline` doesn't affect the linkage. It just allows overcoming the ODR. `constexpr` implies `const`, that translates to internal linkage

**Comment by guoci** [comment]
@federico-busato `inline const` variable has external linkage, if not, what is the point of inline variables?
From https://en.cppreference.com/w/cpp/language/inline:
> Inline const variables at namespace scope have [external linkage](https://en.cppreference.com/w/cpp/language/storage_duration#external_linkage) by default (unlike the non-inline non-volatile const-qualified variables).

See also: https://stackoverflow.com/questions/72934901/inline-constexpr-have-external-linkage

Compiler Explorer [example](https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkAtACIDCAspQNICiA%2BgCEAqgEkAMi34AVAJoAFXgFIAzCxboARgFdgDLAQD2RAA44ANulTiSAO2DaSwdKIAmIAkoBMg74IPatMjGAPLayCbhAGIW6LYkROiM%2BgBmsfSw6K44wahuIACMWGmW%2BUUlcQlJ6AAeCSaWAHQEJiZYoAz6OLSitgTm2q5ZjAAMXbQcJDi2AMqG2qgESQwF4yEmcaP65nbA%2BZ0AlFgQWTmGee5exbH5VxXxiSDoza3tybg9fQND7gxjH5NpnMFktGKsPutNn9trt9gwjidsrl8iprqV3AAWNGVR6ccjocTdZC0RrIGrIN6dD69fqDYbQgFTWbzRbLf7dSG2LZYHb2OEHI7dPEUeSoQwAK3QBGQ3PFhSwtnQAHcYuiQABWI7mRjq/RchmGRjSDDoADU3hU4Jl0IRSCMQ14SPOuHw9yqTzqpiaLTaKUMtmQMwIJEshSxfoDwlo6HkNVl8t5oE8Pj8WGjlmlOH9%2BDirjYhgGRC5XiKucJioActoiJorCBUSZDLQclnbPnC8Wio3m8hW%2BX0FWa3XUempb3/TNkCRUMh29XO2n0Bnx7MpzP%2B4Pa6h62m17OC/OQCXd9PkBvq1v60daCzQQwLdNaUNzSo2AQgtlDKplCNKA%2BvnSL5sIkRDnAAnt%2BSi/tM5jTGaRi2EEtQmKgprTMgppgS%2BLCmioqi%2BL%2BABuhg4K4proBABz4VBlDoaapDTJR5oAOwEZQpocaaH4gCAKHoSkEDeF4DFcko6psMg3jqiYYlsLYQlYFxU69gQ/DBkEqhvv6QSmsRpEAFTfhA3EgCQriuBgtA3gJYEClRKhsZx5GUdRv5KMxLDwjyOp6tyhq1PU3qvNaYy2h4hgOk6qAuhAbqPM8PrFP6gbBqGBThslUYxnGDJylciYeH4qajpm2YnLYeYHkW8plnBm51sxWDdi2/pztVXZNi1tjnkO26NSVK6TqebVckUA2tkN651ReDUnjOI3ykEp49ZezHXreyz/k%2BZqae%2ByCfpBbleCoj7fDtr4geBh2ULUyBWLYpoITpdEQQ5NF6WRFEHCxjmcSZfEBgJQlJLJkleNJsnyV4VxKSQKlqSQGmvk9GEfYZKi8MZ%2B08WZFnoFZhg2XZrl/h5NFedqDC6gqflPC8bQhV5EB2sYZiWNFeCEKzsTbnQ8QmLQCCGBSJR3ag9AQJo3KaNM05gWC%2Bgy/EqBgSEmiStKCsGMYiQBiEtjmPLDJDDowBsCG5j0Cs%2BhDKQ9ihsbOAYJmhH49ytRSuEbJdAGS7crBmioHL%2BZDNyaA4EQCtHCkOx0AAajgyqclrEYpSGSTpUlkbRrG8b5bshUpj4PI4JoGSUVghgmCuVtMCEKimkwADqFuN03t1B23GyuHYKn6IYruoKgpFu5A15LmOrY5hVC2lhVK11h1PatrPTWdSuC/bmNE%2Blauw1VaNi7LhNe6b4te6r0tU2VjNW9HGgmCFFqPk0wajCmjUAAcABsTDfxippgAEAIKaCAaBtC2DIN9CAxpMDmmOgUA4%2BhGZhXtOgR0ZwOauliA8JIwoCREhJGSEWyUgzpzDFnZAWVc65R3AVYg%2BIj6TzKrmBaKgACcWBao316iARqzUVyrwEX2aavDv5MN3pNfcHZ6ycPGhOU%2BojVpzWkYeMaiieGXm/utEEywUISjHMzJc5hDBUTcr%2BXG/APYEHCCQTQlgIDzAiOERotAaJOQCl6BKrR3GcW8SYMxf4joNzXM4ZA/BYKQIiaXIOw98aOPCJEZArjTQpCIPtQJFMX76n%2BIafBhIghEPJFgFBRwyAahGN5BgGJfJvypPQK4KDjgwEQCAJxSSYpGFMDzCs7oGBf1/v/QBwDTQFBUI0LwqRSGpQzhlbO2U84lJNKReUSog4mCjlU6mOT%2B6MDCM4jChMP4/z/gAoBICwGoAgVA0B%2BZuns3gSoLwSCSlbAFFgBA6AzJ1gruU9UlTKY1Nfrk949BKmlKqZM4FuyqQQsHs2bMGIgA%3D%3D)

**Comment by federico-busato** [comment]
Hi @guoci, you are right. I missed that `constexpr` + `inline` has special meaning

**Comment by federico-busato** [comment]
I just realized that I reported the right behavior in slide 22. Anyway, I fixed the mistake. Thanks!
