### ISSUE TITLE
Possible improvements: Basic Concepts III

### ISSUE THREAD

**Issue by leofracca** [federico-busato/Modern-CPP-Programming#43]
Hi Federico,

slide 15/33 of Basic Concepts III states that:
> Contrary to C, C++ does not allow anonymous struct (i.e. without a name)

I think it would be useful to add a note saying that the C++ standard does not allow anonymous structs, but most compilers (gcc, clang, MSVC and others) support them.

See [this post on stackoverflow](https://stackoverflow.com/questions/2253878/why-does-c-disallow-anonymous-structs) and [this post on reddit](https://www.reddit.com/r/cpp/comments/b6xtfu/anonymous_and_unamed_struct/)

**Comment by federico-busato** [comment]
Hi Leonardo, in fact the issue is much deeper than that, and I was not aware of it. Thanks for reporting it. It requires a dedicated slide for the topic 
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/f9fd9aa8-cb15-4ab0-8651-b8ad9064d5d7)
