### ISSUE TITLE
`std::iterator` is deprecated in C++17

### ISSUE THREAD

**Issue by guoci** [federico-busato/Modern-CPP-Programming#45]
In `17.Iterators_Containers_Alg.pdf`, there is an example of implementing an iterator class using `std::iterator`. `std::iterator` is deprecated in C++17 for various reasons.
https://stackoverflow.com/questions/43268146/why-is-stditerator-deprecated

**Comment by federico-busato** [comment]
thanks, @guoci. This is a very good point! I refactored the iterator example to highlight the issue. Please check if it better now.

**Comment by guoci** [comment]
LGTM, although some may disagree with your use of  "template class".
https://stackoverflow.com/questions/879535/what-is-the-difference-between-a-template-class-and-a-class-template

**Comment by federico-busato** [comment]
right. I used both versions. I checked the usage of  "template class" in all slides
