### ISSUE TITLE
Type Deduction - Pass by-Value 

### ISSUE THREAD

**Issue by guoci** [federico-busato/Modern-CPP-Programming#46]
At `18.Advanced_Topics_I.pdf`, slide 45, the last 2 lines should be:
```
    f(y); // T = const int*
    f(z); // T = int* !! (const drop)
```
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/1260178/60fb2a48-738a-4c7e-bfa9-fbc1086d3f84)

**Comment by federico-busato** [comment]
bad error. Thanks for reporting it, @guoci!
