### ISSUE TITLE
22.Optimization_III.pdf, Loop Fission

### ISSUE THREAD

**Issue by guoci** [federico-busato/Modern-CPP-Programming#48]
On slide 31 of `22.Optimization_III.pdf`, the code for loop fission is the same as the code for Loop Fusion in the previous slide.

**Comment by federico-busato** [comment]
thanks for reporting it @guoci. I found a nice example to show the concept
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/47691b87-7af2-4870-a286-f14ec2536c00)
