### ISSUE TITLE
Chapter 2, Page 39: i = 3, should be 2

### ISSUE THREAD

**Issue by AlanDeSmet** [federico-busato/Modern-CPP-Programming#49]
In [chapter 2](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/02.Basic_Concepts_I.pdf), on page 39, the second example reads:

```C++
i = 0;
i = i++ + 2; // until C++17: undefined behavior
             // since C++17: i = 3
```

I believe `i = 2`. GCC 11.4.0 seems to agree:

```
$ cat test.cpp
#include <iostream>

int main() {
        int i = 0;
        i = ++i + 2;
        std::cout << i << "\n";
        i = 0;
        i = i++ + 2;
        std::cout << i << "\n";
}
$ g++ -std=c++17 test.cpp
$ ./a.out 
3
2
```

I got the same behavior with `-std=c++20` and `-std=c++23`.

**Comment by federico-busato** [comment]
Thanks for the interest. I'm using the [en.cppreference.com](en.cppreference.com) style to indicate when something is supported. 
`until C++17` means "before C++17" (C++14, C++03, etc.). 
```
i = 0;
i = i++ + 2; // until C++17: undefined behavior
             // since C++17: i = 3
```
The best way to test undefined behavior is to use a `constexpr` function. If you write these two lines there, you will get an error.
My suggestion is also to take a look at `19.Advanced_Topics_II.pdf` to understand more about undefined behavior
