### ISSUE TITLE
Possible logic error in Floating-point Comparison function

### ISSUE THREAD

**Issue by linomp** [federico-busato/Modern-CPP-Programming#5]
In `02.Basic_Concepts_I.pdf`, on slide 94 inside the function `areFloatNearlyEqual` there is the following code for catching Inf or NaN arguments:
```
if (std::isfinite(a) || isfinite(b))  // a = ±∞, b = ±∞ and NaN
        return false;
```

But it was causing the function to return `false` always, even for finite values. I think it should be:
```
if (!(std::isfinite(a) && std::isfinite(b)))  // a = ±∞, b = ±∞ and NaN
        return false;
```

**Comment by federico-busato** [comment]
thank you, @linomp!! I will fix it in the next release.
