### ISSUE TITLE
Chapter 3, page 50: Was "/" meant where "\" is?

### ISSUE THREAD

**Issue by AlanDeSmet** [federico-busato/Modern-CPP-Programming#51]
In chapter 3, page 50, this line appears:

> _op_ ∈ {+, −, *, \\} denotes exact precision operations

Where `\` appears, was `/` intended? I think _op_ is intended to be the set of basic mathematical operations: add, subtract, multiply, divide. In that case, I'd expected `/` to be used for division instead `\`.

**Comment by federico-busato** [comment]
thanks!
