### ISSUE TITLE
Comparison operator have higher precedence than Bitwise!!! 

### ISSUE THREAD

**Issue by indraneel-mondal** [federico-busato/Modern-CPP-Programming#53]
In the operator precedence slide 1/2, it says
> "Comparison operator have higher precedence  than bitwise and logic operators"

But in the Operator Overview slide 1/3, bitwise operators are placed before relational operators. Also, in the Operator Precedence slide 2/2, `a + b > 3 >> 4` gets interpreted as `(a + b) > (3 >> 4)`. This can only happen if `>>` had higher precedence than `>`.

**Comment by federico-busato** [comment]
thanks, @indraneel-mondal. You are right, good catch.
