### ISSUE TITLE
`19.Advanced_Topics_II.pdf`

### ISSUE THREAD

**Issue by guoci** [federico-busato/Modern-CPP-Programming#59]
On the following slide, `const_cast<int>(var) = 4;` should be changed to `const_cast<int&>(var) = 4;`
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/1260178/ca51ed0c-cd2c-41c7-9e4e-756f395cf4d9)

https://stackoverflow.com/questions/61003855/const-cast-to-non-pointer-non-reference-type

**Comment by federico-busato** [comment]
thanks again @guoci, excellent observation
