### ISSUE TITLE
Possible error in Capture List and Classes

### ISSUE THREAD

**Issue by lopezzot** [federico-busato/Modern-CPP-Programming#6]
Dear Federico,

perhaps an error in `05.Basic_Concepts_IV.pdf` slide 33.
```cpp
auto lambda3 = [this]() { return data; }; // copy by-reference, return 2
```
it returns 1, not 2. 
For instance, the following prints 1 with `-std=c++20`:
```cpp
#include <iostream>

class A {
    public:
        int data = 1;

        void f(){
            int var = 2;
            auto lambda3 = [this](){return data;};
            std::cout<<lambda3()<<std::endl;
        }
};   

int main(){
    A a;
    a.f();
    return 0;
}
```

**Comment by lopezzot** [comment]
And perhaps another little mistake in `03.Basic_Concepts_II.pdf` slide 17.
```cpp
struct A {int x; int y;};
A array[10] = { {1,2}, {5,6}, {7,1} };
for (auto [x1, y1] : array) cout<<x1<<","<<y1<<" "; //print:1,2 5,6 7,1
```
I suppose it is `A array[]` instead of `A array[10]`. Otherwise it prints
```
1 2
5 6
7 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
```

**Comment by lopezzot** [comment]
And maybe another one in `07.Object_Oriented_II.pdf` slide 26.
```cpp
static_cast<B&>(a1).f(); // print "A" downcasting
```
It actually prints "B", not "A". I suppose you meant:
```cpp
static_cast<B&>(a).f(); // print "A" downcasting
```

**Comment by federico-busato** [comment]
Hi @lopezzot, many thanks for pointing out all these issues. I will fix them soon.

**Comment by lopezzot** [comment]
You are welcome and thanks for this excellent course.
