### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by Wheest** [federico-busato/Modern-CPP-Programming#63]
Thanks for the course material!  Here I'm listing minor spelling errors I encounter as I review the material.  These are just ones that jumped out to me, rather than a systematic review, e.g., using a tool such as [codespell](https://github.com/codespell-project/codespell)

**Entities:**

> A C++ program is set of language-specif keywords

A C++ program is **a** set of language-**specific** keywords

**Dynamic Memory Allocation and OS:**

> A program does not directly allocate memory itself but it asks for a chuck of memory to the OS.

Should be "**chunk** of memory **from** the OS".

____

I'll add additional comments to this issue if I find any more as I go through the course

**Comment by federico-busato** [comment]
thanks, @Wheest for the suggestion and to point out the typos. I was able to integrate even [LanguageTool](https://languagetool.org/) in my Tex editior. 
Interestingly, `A C++ program is set of language-specif keywords`  is not caught by any tool 🤔

**Comment by Wheest** [comment]
Thanks for pushing the changes.  I've noticed in Code Conventions, there is a typo in Control Flow, where the comments which should read "Correct" and written as "Corret".
