### ISSUE TITLE
Typo in 02.Basic_Concepts_I.pdf

### ISSUE THREAD

**Issue by LuccaT95** [federico-busato/Modern-CPP-Programming#65]
On p.39 in 02.Basic_Concepts_I.pdf there is the example 
```
i = 0
a[i] = i++ // since C++17 a[1] = 1
```
I believe it should be `++i` in the above? I tried with `a` being `std::vector<int>` in C++17 and C++20.

Thank you for writing this material!

**Comment by federico-busato** [comment]
thanks again @LuccaT95! you are right!
