### ISSUE TITLE
Typo in 02.Basic_Concepts_I.pdf

### ISSUE THREAD

**Issue by ilovexyz** [federico-busato/Modern-CPP-Programming#66]
On page 26, the code example note said "nullptr is a pointer"

`int* p2 = nullptr; // ok, nullptr is a pointer not a number`
 
however, the bottom of the slide said "Remember: nullptr is not a pointer, but an object of type nullptr t → safer", this conflicts with above comment.

**Comment by federico-busato** [comment]
@ilovexyz that's a good point. I also took the opportunity to reorganize a bit the slide
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/22839f2f-2042-4eb8-9cb2-89563ccb909e)
