### ISSUE TITLE
Code Fix in 05.Basic_Concepts_IV.pdf

### ISSUE THREAD

**Issue by liyixin123** [federico-busato/Modern-CPP-Programming#69]
Hello Federico,
On page 46, when I run the example , after *c++, a is equal to 3 instead of 4. I'm not sure if this is due to my mistake or not.

![829FB6E0-0F20-4b71-BDE8-DC3CCF14872E](https://github.com/federico-busato/Modern-CPP-Programming/assets/56808175/2a380ef9-7a7d-40a2-b9b2-f5ca2419ebcb)

**Comment by federico-busato** [comment]
Hi @liyixin123, you are right. I forgot the parenthesis for `(*c)++`. I will replace post-increment with pre-increment to avoid confusion
<img width="459" alt="image" src="https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/466b909d-e161-44a3-a40f-ce62ae9a7b42">
