### ISSUE TITLE
C++ Journey 

### ISSUE THREAD

**Issue by Ekenechuk** [federico-busato/Modern-CPP-Programming#7]
#include<iostream>
using namespace std;

int main(){
cout >> " Hello World" >> endl;
return 0;
}

**Comment by federico-busato** [comment]
?

**Comment by Ekenechuk** [comment]
> ?

There is this website I tried coding this and it displayed error, please what could be the problem?

**Comment by caporalesimone** [comment]
You shout write curt << "hello world" and not >>
