### ISSUE TITLE
Fix in 13.Code_Convention.pdf

### ISSUE THREAD

**Issue by leofracca** [federico-busato/Modern-CPP-Programming#71]
Hi Federico,
on page 34, the second example
`# if define(MACRO1) && defined(MACRO2)`
should be change to
`# if defined(MACRO1) && defined(MACRO2)`

Moreover, on page 60 the first bullet point contains "whatever" in the sentence, but I believe it should be "whenever" instead.

**Comment by federico-busato** [comment]
Hi @leofracca, thanks again. Both hard to catch.
