### ISSUE TITLE
Char type one's complement?

### ISSUE THREAD

**Issue by marcobergamin** [federico-busato/Modern-CPP-Programming#8]
Hello Federico,

In the document 02.Basic_Concepts_I.pdf, on slide 18/100, you have written that `char` is a one's complement type with a range from -127 to 127, and I believe this is incorrect. The range could be either the same as `signed char` or `unsigned char`, depending on the platform. For example, the range with x86 processors is -128 to 127 (example here: https://godbolt.org/z/G9MYbhGfd). On ARM processors, it is from 0 to 255.

Best regards,
Marco

**Comment by federico-busato** [comment]
Hi Marco, good catch! Thank you for reporting. You are definitely right. The standard doesn't force signed or unsigned for the `char` data type https://en.cppreference.com/w/cpp/language/types. I will fix it in the next release.
