### ISSUE TITLE
Proposed rewording for "3. Basic Concepts II", example on page 21

### ISSUE THREAD

**Issue by binary-manu** [federico-busato/Modern-CPP-Programming#80]
The provided example says:

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/47382117/136516e6-d0bd-4822-bac2-54894ad03181)

However, if the `if` were to be removed entirely, we would be able to call the function with any negative index and it would be used to access the array, without any checks.

What actually happens (at least with `clang` when compiling with `-O3`) is that the code is generated as follows:

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/47382117/6c86fa48-a7d6-46f4-8974-e2b92b8d6f9d)

The `if` statement is still there, in form of a `jl` opcode, but instead of checking if the parameter is negative after the increment, it checks if it's smaller than -1 before the increment. This makes sense, since the only way to get a negative number after an increment, if we ignore overflow, is to start with a number lower than -1. This code thus crashes if the passed index is `INT_MAX`.

As a side note, `gcc` generates it differently,:

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/47382117/a2477a61-762f-4ac1-b2b5-f13958f7884b)

and thus it will not crash in this example.

So I would propose to reword the comment not to mention the removal of the `if` statement, since it must remain to prevent real negative indices from being used.

**Comment by federico-busato** [comment]
thanks for the detailed explanation, @binary-manu. I did some experiments with compiler-explorer and I reorganized the slide as follow 
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/d687e69d-c45c-4597-a596-d780aae8090b)
