### ISSUE TITLE
Table of contents broken in all-in-one modern-cpp.pdf

### ISSUE THREAD

**Issue by eugenefil** [federico-busato/Modern-CPP-Programming#84]
After reading much of the course I'm using all-in-one modern-cpp.pdf to quickly jump between topics back and forth - very convenient. But at some places the table of contents is broken:

1. The whole chapter "6. Basic Concepts V" starting with "Functions" and up to the first topic "C++ Classes" of chapter "7. Object-Oriented Programming I" are buried in the table of contents under the topic "Constants, Literals, const, constexpr, consteval, constinit" of the preceding chapter "5. Basic Concepts IV".

![screen1](https://github.com/federico-busato/Modern-CPP-Programming/assets/33426868/04bc6d49-d137-4aa6-b257-0dc262f96caa)

2. In a similar vein, but more convoluted, the whole section of table of contents between top-level "Execution Debugging" and "View" is garbled. Here chapter "15. C++ Ecosystem" starting with "CMake" is buried under "Execution Debugging" of chapter 14. And chapter "16. Utilities" starting with "I/O Stream" is under topic "Other Tools" of ch.15. Chapter "17. Containers, Iterators, Ranges, and Algorithms" starts under "Time Measuring" of ch.16.

![screen2](https://github.com/federico-busato/Modern-CPP-Programming/assets/33426868/353a0ce8-7327-4923-b916-aee9eee7f5c4)

3. The first topic "I/O Operations" of Chapter "21. Performance Optimization II" is buried under the last topic "Memory Concepts" of ch.20.

Thanks!

**Comment by federico-busato** [comment]
Thanks for reporting it, @eugenefil. Not sure why this happened. I regenerate the file and looks fixed

**Comment by eugenefil** [comment]
The first one is fixed, thanks a lot. But the 2nd and 3rd are still there. The 2nd is particularly messed up for some reason. E.g. try expanding "Execution Debugging" and you'll see "CMake" under it. Then further expand "Other Tools" and you'll see "I/O Stream".

**Comment by federico-busato** [comment]
I regenerate everything from scratch. This should fix the issue

**Comment by eugenefil** [comment]
It really did. Thanks a lot!
