### ISSUE TITLE
Extra empty line is processed in "I/O Stream - Example 1"

### ISSUE THREAD

**Issue by eugenefil** [federico-busato/Modern-CPP-Programming#85]
On p.14 of file 16.Utilities.pdf under title "I/O Stream - Example 1" the line-by-line reading code will process extra empty line if either:
- file is empty - because fin.good() is true before first std::getline
- the last line in file ends with a newline - because reading will stop at that newline and eofbit will be set only by the next getline

The fix is basically described in the [reading-files-in-c-using-ifstream link](https://gehrcke.de/2011/06/reading-files-in-c-using-ifstream-dealing-correctly-with-badbit-failbit-eofbit-and-perror/) provided later on p.16:
```diff
     std::string str;
-    while (fin.good()) {
-        std::getline(fin, str);
+    while (std::getline(fin, str)) {
         std::cout << str << "\n";
```

Or even shorter:
```diff
-    std::string str;
-    while (fin.good()) {
-        std::getline(fin, str);
+    for (std::string str; std::getline(fin, str);) {
         std::cout << str << "\n";
```

`while (getline)` won't execute body if nothing was read, because getline sets failbit on the returned stream in this case. And with the failbit set, the stream, when cast to bool, evaluates to false.

**Comment by federico-busato** [comment]
thanks! The link that you added provides so many insights about the topic. I added it at the end of the page

**Comment by eugenefil** [comment]
It really does. Note, you've provided that same link also on p.16 "I/O Stream -Check the End of a File", I found it there. Now there are 2 identical links: on p.14 (new) and on p.16 (old). Probably p.14 is really a better place for it, but it's up to you.

**Comment by federico-busato** [comment]
thanks!
