### ISSUE TITLE
Valid overloaded function call marked as error (6. Basic Concepts V)

### ISSUE THREAD

**Issue by binary-manu** [federico-busato/Modern-CPP-Programming#86]
This page says:

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/47382117/b3c208f8-3ad1-422d-b212-7de84ee62b28)

but then the call taking a single `char` literal is marked as an error. However, it does compile.

Of the available overloads of `f`, only 2 can be called with a single argument, but `f(float)` implies a conversion, while `f(int)` uses integral promotions, as listed in the rule bullets. Thus, `f(int)` is selected since it has higher priority.

```c++
#include <iostream>

void f(int a) {
    std::cout << "int here!\n";
}

void f(float b) {
    std::cout << "float here!\n";
}

void f(float b, char c) {
    std::cout << "float and char here!\n";
}

int main() {
    f(0);
    f('a');
    f(2.3f);
    //f(2.3);
    f(2.3, 'a');
}

/*
Output:

int here!
int here!
float here!
float and char here!
*/
```

**Comment by federico-busato** [comment]
thanks, @binary-manu. Definitely a mistake on my side. Here the slide updated with some improvements
<img width="427" alt="image" src="https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/c12ab886-f8e8-4e0c-803c-279e9371684c">
