### ISSUE TITLE
Macro redefinition without #undef triggers warning (07. Basic_Concepts V)

### ISSUE THREAD

**Issue by binary-manu** [federico-busato/Modern-CPP-Programming#88]
This example says:

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/47382117/0e1d4559-fc55-4547-9bb3-5ec38dd842f5)

However, as per [cppreference.com](https://en.cppreference.com/w/cpp/preprocessor/replace):

> The #define directives define the identifier as macro, that is instruct the compiler to replace most successive occurrences of identifier with replacement-list, which will be additionally processed. Exceptions arise from the rules of [scanning and replacement](https://en.cppreference.com/w/cpp/preprocessor/replace#Scanning_and_Replacement). If the identifier is already defined as any type of macro, the program is ill-formed unless the definitions are identical.

Both GCC and clang will show a warning when compiling:

```c++
foo.cc:11: warning: "value" redefined
   11 | # define value 3
      | 
foo.cc:4: note: this is the location of the previous definition
    4 | # define value 4
      | 
```

**Comment by federico-busato** [comment]
Hi Emanuele, in my experience and especially with automated builds in CI/CD, warnings are almost useless. I can point out that common compilers raise a warning for this problem

**Comment by binary-manu** [comment]
Sure. I pointed this out because it ringed a bell and a project I recently worked on actively tried to minimize warnings, so maybe better let newcomers to the language know they will get a warning and how to get rid of it if required.
