### ISSUE TITLE
Request: uploading HTML version to githubpages via CI

### ISSUE THREAD

**Issue by russkel** [federico-busato/Modern-CPP-Programming#89]
I am unable to view the HTML version from the github interface. I think it would be nice to publish it to a github pages upon commit. This will also allow proper search engine indexing which I assume isn't happening via git repo files.

**Comment by federico-busato** [comment]
that's a great idea!! I will try to set up everything with github pages

**Comment by russkel** [comment]
I believe there's plenty of recipes around that you could derive your solution from :)

**Comment by federico-busato** [comment]
it was super easy! thanks again for the great suggestion!

**Comment by russkel** [comment]
Thanks for the quality content @federico-busato
