### ISSUE TITLE
Why not write a Book already (One PDF book including all these PDF chapters)

### ISSUE THREAD

**Issue by RayyanNafees** [federico-busato/Modern-CPP-Programming#9]

**Comment by federico-busato** [comment]
Thank you. This is a great idea, but I hardly have the time to keep updating the slides. Maybe in the future I could also consider making the latex source available to everyone.

**Comment by caporalesimone** [comment]
A suggestion: why don't you push only the latex version and use a GitHub action to release all in one versioned pdf?

**Comment by federico-busato** [comment]
Maybe I misunderstood your request. Are you just asking to provide a single pdf with all chapters merged? 
Initially, I thought about an entire layout reorganization to fit Letter/A4 page

**Comment by caporalesimone** [comment]
My suggestions are 

1- release a latex so is more simple to open a PR to help you on fixing errors (if you like this approach)

2- use a GitHub action that automatically creates one single pdf A4 style every time you do a release so you don't have to take care of releasing manually the pdfs each time.

**Comment by federico-busato** [comment]
thanks for the suggestions. Making everything open source is a big step and quite hard to accept after spending so many hours on this course. Anyway, I will consider it for the future
