### ISSUE TITLE
Question in data movement calculation in 21.Optimization_I.pdf

### ISSUE THREAD

**Issue by xintin** [federico-busato/Modern-CPP-Programming#90]
In [slide 29/62](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/21.Optimization_I.pdf), it states that the data movement in a naive mm is `(N^2 . 4B) . 3`

I think it should be  `(N^3 . 4B) . 3`

Explanation: 
- Each element of A and B is accessed N times for each element of C.
- A and B have `N^2` elements, each accessed N times, so `N^3`.
- C has `N^2` elements; each element is written N times (accumulated value), so `N^3`.

Assuming each floating point is `B` bytes (usually, `B=4` for single precision or `B=8` for double precision).

Total data movement in bytes is approximately = `3 . N^3 . B`

**Comment by federico-busato** [comment]
Well, I see your point. On the other hand, this is a more high-level asymptotic analysis. The data movement is intended to be the amount of data accessed from main (slowest) memory. We are looking at an "ideal" system. Actual data movement really depends on the problem sizes and hardware details, such as cache sizes. I'm not aware of any scientific work that provides a rigorous bound on data movement.

**Comment by xintin** [comment]
I agree with your points. But what I was referring to is something similar to [this slide](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://people.eecs.berkeley.edu/~demmel/cs267_Spr12/Lectures/lecture02_memhier_jwd12&ved=2ahUKEwiipMqRq7WFAxU6ElkFHWFyBJgQFnoECBQQAQ&usg=AOvVaw13tUo-L7q-5NWJtwPtwzJs), slides 40-41. And your analysis is similar to slide 39 in the mentioned deck. 

I think the figures used in James Demmel's slides are more intuitive. 

> I'm not aware of any scientific work that provides a rigorous bound on data movement.    

If interested, there is excellent work by Hong/Kung, Irony et al., and Ballard on this topic. (obviously, out of scope here).

Lastly, thanks again for this wonderful compilation. This repo is so resourceful.

**Comment by xintin** [comment]
Looks great. Thank you @federico-busato
