### ISSUE TITLE
Possibly a minor typo in title (10.Template_I.pdf)

### ISSUE THREAD

**Issue by abzrg** [federico-busato/Modern-CPP-Programming#91]
Hi,

10.Template_I.pdf: Page 17, slide number: 15/48

Change: Adding s to Parameter

```diff
-Default Parameter
+Default Parameters
```

**Comment by federico-busato** [comment]
Hi @abzrg, thanks for reporting the issue. I don't see the text `Default Parameter` in this lecture. Are you reading the latest version?

**Comment by abzrg** [comment]
Sorry, I was tired last night and I've copy-pasted the wrong piece of text (:

This is the typo

```diff
-Template Parameter
+Template Parameters
```

**Comment by federico-busato** [comment]
good catch! thanks
