### ISSUE TITLE
Request STL chapter and lambda function

### ISSUE THREAD

**Issue by RuimingShen** [federico-busato/Modern-CPP-Programming#92]
Thanks for this very detailed C++ study source! Could you please add a chapter about STL? Also lambda function in C++ is a little bit confusing to me. Could you please add it? Thanks!

**Comment by federico-busato** [comment]
Thanks for the interest in the course! There are two main chapters related to STL [17. Utilites](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/17.Utilities.pdf) and [18.Iterators_Containers_Alg](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/18.Iterators_Containers_Alg.pdf), while for lambda expression you can take a look at [7. Basic Concepts V](https://github.com/federico-busato/Modern-CPP-Programming/blob/master/07.Basic_Concepts_V.pdf)
