### ISSUE TITLE
Code fix for sizeof examples in 05.Basic_Concepts_IV

### ISSUE THREAD

**Issue by Mati-as** [federico-busato/Modern-CPP-Programming#93]
Hello Federico

Encountered the compile error with these examples below,  the page 78, on 0.5.Basic_Concept.pdf.
Declaring a function parameter as 'int[] array' might seem more like a C# syntax and also require specifying the size of the array to fix compile errors (e.g. ```void f(const int(&array)[10])```

I'm uncertain if using 'int[] array' was an intentional educational choice or if it's a misunderstanding on my part. Could you please clarify this?
 

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/120005151/5f8288c0-bae1-4d1d-bb40-559d362719a4)

**Comment by federico-busato** [comment]
Hi @Mati-as, yes, this is a typo. The intention is to use `f(int array[])` to show that the syntax is bug prone.
