### ISSUE TITLE
Report: there is typo in 05.Baisic_Concepts_IV

### ISSUE THREAD

**Issue by ChoiSeonMun** [federico-busato/Modern-CPP-Programming#94]
Hi, Fedrico.

First of all, thank you for providing the material. I'm using it well to study with my friends.
But, I guess there is an error on the 80th slide.

![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/17216686/8e40c040-4964-4639-9fc1-75c6f8dc6c33)

The slide says `sizeof(array1) is 1`. but, the actual result is 10.
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/17216686/2947eac8-171c-4b39-9177-5fef4719a114)

Would you check this?

**Comment by federico-busato** [comment]
Hi @ChoiSeonMun, you are right! Thanks for reporting it
