### ISSUE TITLE
Minor typo in 05.Basic_Concepts_III.pdf

### ISSUE THREAD

**Issue by viktorteren** [federico-busato/Modern-CPP-Programming#95]
Hi,

it seems that on page 17/38 of 05.Basic_Concepts_III.pdf there is a typo in the **last** comment:

```diff
- // sizeof(S1): 8 bytes
+ // sizeof(S2): 8 bytes
```

**Comment by federico-busato** [comment]
Hi @viktorteren, thanks for reporting it.
