### ISSUE TITLE
Question : I'm a little confused about the content of the 28th slide of Basic Concepts V

### ISSUE THREAD

**Issue by ChoiSeonMun** [federico-busato/Modern-CPP-Programming#96]
Hi there.

I came here because I was studying and had trouble understanding something intuitively.
The 28th slide says that `A function can return a lambda (dynamic dispatch is also possible)`
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/17216686/515129e0-6e10-493a-bcdc-50dba19c90a6)

I'm wondering if the code below describes your intent.

```cpp
auto f(int type) -> bool(*)(int, int)
{
    if (type % 2 == 0)
    {
        return [](int lhs, int rhs) { return lhs < rhs; };
    }
    else
    {
        return [](int lhs, int rhs) { return lhs > rhs; };
    }
}
```

If my understanding is not correct, could you unpack it a bit more and explain?

**Comment by federico-busato** [comment]
Hi @ChoiSeonMun, your understanding is correct. Note that you can only return a lambda as a function pointer `bool(*)(int, int)` only if it doesn't capture anything. Otherwise, dynamic dispatching will not work. I may need to clarify this point in the slides.
