### ISSUE TITLE
Enhancement in 10.Templates_I.pdf

### ISSUE THREAD

**Issue by leofracca** [federico-busato/Modern-CPP-Programming#98]
Hi Federico,
I think it could be useful to add a note somewhere to say that `template<typename T>` is the same as `template<class T>`, even if less used.

**Comment by federico-busato** [comment]
Hi Leonardo, it is in the first slide that mentions the template syntax
![image](https://github.com/federico-busato/Modern-CPP-Programming/assets/55920584/3a500100-6f21-4193-a7b8-b770e19d58f0)

**Comment by leofracca** [comment]
Ops, sorry. I missed that
